server:
  servlet:
    context-path: /blogi
spring:
  mvc:
    view:
      suffix: .html
  web:
    resources:
      static-locations:
        - classpath:/html/dummy
        - classpath:/js/dummy
        - classpath:/css/dummy
        - classpath:/css/home-page
        - classpath:/css
        - classpath:/html/home-page
        - classpath:/js/data
        - classpath:/js/service
        - classpath:/js/home-page
        - classpath:/css/home-page
        - classpath:/js/home-page/filter
        - classpath:/js/rest-api-caller
        - classpath:/js/page-components-generator
        - classpath:/js/events
        - classpath:/html/editor-page
        - classpath:/js/editor-page
        - classpath:/html/single-article-page
        - classpath:/html/sign-in-page
        - classpath:/css/sign-in-page
        - classpath:/js/single-article-page
        - classpath:/css/single-article-page
        - classpath:/css/global-component
        - classpath:/js/global-component
        - classpath:/html/global-component
        - classpath:/images
        - classpath:/html/new-article-page
        - classpath:/css/new-article-page
        - classpath:/js/home-page/components
        - classpath:/js/redirector
        - classpath:/js/new-article-page
        - classpath:/html/redirector
        - classpath:/js/browser
        - classpath:/js/executor
        - classpath:/js/error-page
        - classpath:/js/permission-denied-page
        - classpath:/html/error-page
        - classpath:/html/permission-denied-page
        - classpath:/css/editor-page
        - classpath:/css/permission-denied-page
        - classpath:/css/error-page