server:
  servlet:
    context-path: /blogi
spring:
  mvc:
    view:
      suffix: .html
  web:
    resources:
      static-locations:
        - classpath:/html/dummy
        - classpath:/js/dummy
        - classpath:/css/dummy
        - classpath:/css/home-page
        - classpath:/css
        - classpath:/html/home-page
        - classpath:/js/data
        - classpath:/js/service
        - classpath:/js/home-page
        - classpath:/css/home-page
        - classpath:/js/home-page/filter
        - classpath:/js/rest-api-caller
        - classpath:/js/page-components-generator
        - classpath:/js/events
        - classpath:/html/editor-page
        - classpath:/js/editor-page
        - classpath:/html/single-article-page
        - classpath:/js/single-article-page
        - classpath:/css/single-article-page