server:
  servlet:
    context-path: /blogi
spring:
  mvc:
    view:
      suffix: .html
  web:
    resources:
      static-locations:
        - classpath:/html/dummy
        - classpath:/js/dummy
        - classpath:/css/dummy
        - classpath:/html/home-page
        - classpath:/css
        - classpath:/js/home-page
        - classpath:/css/home-page
        - classpath:/js/rest-api-caller
        - classpath:/js/page-components-generator